export const pagesContent = {
  home: {
    metadata: {
      title: 'Visual portfolios and professional profiles',
      description: 'Discover image-led work, professional profiles, and useful creative resources in one polished browsing experience.',
      openGraphTitle: 'Visual portfolios and professional profiles',
      openGraphDescription: 'Browse image-led work, creative profiles, and useful public posts through a clean discovery experience.',
      keywords: ['visual portfolio', 'creative profiles', 'image gallery', 'professional discovery'],
    },
    hero: {
      badge: 'Creative discovery',
      title: ['Your Future Begins at', 'Our University'],
      description: 'Explore image-led stories, portfolio updates, and professional profiles through a clean browsing system inspired by premium education and gallery sites.',
      primaryCta: { label: 'Explore visuals', href: '/image' },
      secondaryCta: { label: 'Browse profiles', href: '/profile' },
      searchPlaceholder: 'Search visuals, profiles, categories, and posts',
      focusLabel: 'Focus',
      featureCardBadge: 'portfolio rotation',
      featureCardTitle: 'Fresh visual posts shape the homepage experience.',
      featureCardDescription: 'Recent images and profiles stay at the center without changing the underlying content workflow.',
    },
    intro: {
      badge: 'About the platform',
      title: 'Built for browsing visual work and discovering people behind it.',
      paragraphs: [
        'The site brings together images, profiles, articles, and supporting resources in a single public experience.',
        'Visitors can move from visual inspiration to professional context without losing their place.',
        'Every section keeps the original post data intact while presenting it through a more distinctive interface.',
      ],
      sideBadge: 'At a glance',
      sidePoints: [
        'Image-first discovery for portfolios and visual stories.',
        'Profile pages that remain readable even with partial data.',
        'Search, categories, and pagination kept in place.',
        'Responsive layouts with polished empty and loading states.',
      ],
      primaryLink: { label: 'Browse images', href: '/image' },
      secondaryLink: { label: 'See profiles', href: '/profile' },
    },
    cta: {
      badge: 'Start exploring',
      title: 'Find visuals, profiles, and public posts through one connected experience.',
      description: 'Move between image-led posts, profiles, articles, and resources with a clearer visual rhythm.',
      primaryCta: { label: 'Browse Images', href: '/image' },
      secondaryCta: { label: 'Contact', href: '/contact' },
    },
    taskSection: {
      heading: 'Latest {label}',
      descriptionSuffix: 'Browse the newest posts in this section.',
    },
  },
  about: {
    badge: 'Our Story',
    title: 'A sharper home for creative discovery.',
    description: 'golgator helps visitors browse visual work, professional profiles, and useful public posts with less friction.',
    paragraphs: [
      'The experience is designed around strong imagery, clear cards, and simple movement between sections.',
      'Whether someone starts with a portfolio image, a profile, or a resource page, the site keeps discovery connected.',
    ],
    values: [
      { title: 'Image-led browsing', description: 'Visual posts receive enough space to feel considered and easy to inspect.' },
      { title: 'Profile context', description: 'Professional details stay readable and useful even when some optional fields are missing.' },
      { title: 'Simple structure', description: 'Search, categories, detail pages, and related content remain familiar and dependable.' },
    ],
  },
  contact: {
    eyebrow: 'Contact golgator',
    title: 'Tell us what you want to publish, showcase, or improve.',
    description: 'Share the context and the site will keep your request organized through the existing contact workflow.',
    formTitle: 'Send a message',
  },
  search: {
    metadata: { title: 'Search', description: 'Search posts, visuals, profiles, categories, and content across the site.' },
    hero: {
      badge: 'Search the archive',
      title: 'Find visuals, profiles, and resources faster.',
      description: 'Use keywords, categories, and content types to discover posts from every active section.',
      placeholder: 'Search by keyword, topic, category, or title',
    },
    resultsTitle: 'Latest searchable content',
  },
  create: {
    metadata: { title: 'Create', description: 'Create and submit new content for the site.' },
    locked: { badge: 'Creator access', title: 'Login to create new content.', description: 'Use your account to open the publishing workspace and create posts.' },
    hero: { badge: 'Publishing workspace', title: 'Create content for every active section.', description: 'Choose the content type, add details, and prepare a clean post with images, links, summary, and body content.' },
    formTitle: 'Content details',
    submitLabel: 'Submit content',
    successTitle: 'Content submitted successfully.',
  },
  auth: {
    login: {
      metadataDescription: 'Login page for this site.',
      badge: 'Member access',
      title: 'Welcome back to your publishing space.',
      description: 'Login to continue browsing, managing submissions, and creating new content.',
      formTitle: 'Login',
      submitLabel: 'Continue',
      noAccount: 'No account matched these details. Create an account first, then login.',
      success: 'Login successful. Redirecting...',
      createCta: 'Create an account',
    },
    signup: {
      metadataDescription: 'Signup page for this site.',
      badge: 'Site access',
      title: 'Create your account and start publishing.',
      description: 'Create an account to access the publishing workspace and submit content.',
      formTitle: 'Create account',
      submitLabel: 'Create account',
      passwordShort: 'Use at least 4 characters for the password.',
      success: 'Account created successfully. Redirecting...',
      loginCta: 'Login',
    },
  },
  detailPages: {
    article: { relatedTitle: 'Related articles', fallbackTitle: 'Article details' },
    listing: { relatedTitle: 'Related listings', fallbackTitle: 'Listing details' },
    image: { relatedTitle: 'Related visuals', fallbackTitle: 'Image details' },
    profile: { relatedTitle: 'Suggested profiles', fallbackDescription: 'Profile details will appear here once available.', visitButton: 'Visit Official Site' },
  },
} as const
