export const pagesContent = {
  home: {
    metadata: {
      title: 'Visual stories and creative inspiration',
      description: 'Discover image-led work, creative stories, and useful resources in one bold browsing experience.',
      openGraphTitle: 'Visual stories and creative inspiration',
      openGraphDescription: 'Browse image-led work, creative stories, and useful public posts through a bold discovery experience.',
      keywords: ['visual stories', 'creative inspiration', 'image gallery', 'visual discovery'],
    },
    hero: {
      badge: 'Creative discovery',
      title: ['Work On', 'Your Terms'],
      description: 'Fresh perspectives, visual inspiration and practical ideas for independent people building meaningful careers.',
      primaryCta: { label: 'Explore visuals', href: '/image' },
      secondaryCta: { label: 'Browse stories', href: '/image' },
      searchPlaceholder: 'Search visuals, stories, categories, and posts',
      focusLabel: 'Focus',
      featureCardBadge: 'portfolio rotation',
      featureCardTitle: 'Fresh visual posts shape the homepage experience.',
      featureCardDescription: 'Recent images and stories stay at the center without changing the underlying content workflow.',
    },
    intro: {
      badge: 'About the platform',
      title: 'Built for browsing visual work and discovering the ideas behind it.',
      paragraphs: [
        'The site brings together images, stories, articles, and supporting resources in a single public experience.',
        'Visitors can move from visual inspiration to deeper context without losing their place.',
        'Every section keeps the original post data intact while presenting it through a more distinctive interface.',
      ],
      sideBadge: 'At a glance',
      sidePoints: [
        'Image-first discovery for portfolios and visual stories.',
        'Clean pages that remain readable even with partial data.',
        'Search, categories, and pagination kept in place.',
        'Responsive layouts with polished empty and loading states.',
      ],
      primaryLink: { label: 'Browse images', href: '/image' },
      secondaryLink: { label: 'See stories', href: '/image' },
    },
    cta: {
      badge: 'Start exploring',
      title: 'Find visuals, stories, and public posts through one connected experience.',
      description: 'Move between image-led posts, stories, articles, and resources with a clearer visual rhythm.',
      primaryCta: { label: 'Browse Images', href: '/image' },
      secondaryCta: { label: 'Contact', href: '/contact' },
    },
    taskSection: {
      heading: 'Latest {label}',
      descriptionSuffix: 'Browse the newest posts in this section.',
    },
  },
  about: {
    badge: 'Our Story',
    title: 'A sharper home for creative discovery.',
    description: 'Golgator helps visitors browse visual work, creative stories, and useful public posts with less friction.',
    paragraphs: [
      'The experience is designed around strong imagery, clear cards, and simple movement between sections.',
      'Whether someone starts with a portfolio image, a story, or a resource page, the site keeps discovery connected.',
    ],
    values: [
      { title: 'Image-led browsing', description: 'Visual posts receive enough space to feel considered and easy to inspect.' },
      { title: 'Clear context', description: 'Content details stay readable and useful even when some optional fields are missing.' },
      { title: 'Simple structure', description: 'Search, categories, detail pages, and related content remain familiar and dependable.' },
    ],
  },
  contact: {
    eyebrow: 'Get in touch',
    title: 'Tell us what you want to publish, showcase, or improve.',
    description: 'Share the context and the site will keep your request organized through the existing contact workflow.',
    formTitle: 'Send a message',
  },
  search: {
    metadata: { title: 'Search', description: 'Search posts, visuals, stories, categories, and content across the site.' },
    hero: {
      badge: 'Search the archive',
      title: 'Find visuals, stories, and resources faster.',
      description: 'Use keywords, categories, and content types to discover posts from every active section.',
      placeholder: 'Search by keyword, topic, category, or title',
    },
    resultsTitle: 'Latest searchable content',
  },
  create: {
    metadata: { title: 'Create', description: 'Create and submit new content for the site.' },
    locked: { badge: 'Creator access', title: 'Login to create new content.', description: 'Use your account to open the publishing workspace and create posts.' },
    hero: { badge: 'Publishing workspace', title: 'Create content for every active section.', description: 'Choose the content type, add details, and prepare a clean post with images, links, summary, and body content.' },
    formTitle: 'Content details',
    submitLabel: 'Submit content',
    successTitle: 'Content submitted successfully.',
  },
  auth: {
    login: {
      metadataDescription: 'Login page for this site.',
      badge: 'Member access',
      title: 'Welcome back to your publishing space.',
      description: 'Login to continue browsing, managing submissions, and creating new content.',
      formTitle: 'Login',
      submitLabel: 'Continue',
      noAccount: 'No account matched these details. Create an account first, then login.',
      success: 'Login successful. Redirecting...',
      createCta: 'Create an account',
    },
    signup: {
      metadataDescription: 'Signup page for this site.',
      badge: 'Site access',
      title: 'Create your account and start publishing.',
      description: 'Create an account to access the publishing workspace and submit content.',
      formTitle: 'Create account',
      submitLabel: 'Create account',
      passwordShort: 'Use at least 4 characters for the password.',
      success: 'Account created successfully. Redirecting...',
      loginCta: 'Login',
    },
  },
  detailPages: {
    article: { relatedTitle: 'Related articles', fallbackTitle: 'Article details' },
    listing: { relatedTitle: 'Related listings', fallbackTitle: 'Listing details' },
    image: { relatedTitle: 'Related visuals', fallbackTitle: 'Image details' },
    profile: { relatedTitle: 'Suggested posts', fallbackDescription: 'Details will appear here once available.', visitButton: 'Visit Official Site' },
  },
} as const
